<?php //ICB0 81:0 82:1cf7                                                     ?><?php //00fb1
// -------------------------------------------------------------------- //
// ++++++++++++++++++++++ Website: www.BeGPL.com ++++++++++++++++++++++ //
// -------------------------------------------------------------------- //
//                    ____        _____ _____  _                        //
//                   |  _ \      / ____|  __ \| |                       //
//                   | |_) | ___| |  __| |__) | |                       //
//                   |  _ < / _ \ | |_ |  ___/| |                       //
//                   | |_) |  __/ |__| | |    | |____                   //
//                   |____/ \___|\_____|_|    |______|                  //
//                                                                      //
// -------------------------------------------------------------------- //
// Your Ultimate Source of GPL WordPress Plugins, Themes, Modules, and  //
// PHP Scripts, BeGPL operates as a digital marketplace that provides   //
// access to a wide range of premium themes, plugins, scripts and other //
// digital products for web creatives.                                  //
// -------------------------------------------------------------------- //
//                                                                      //
//    _         _         _         _         _         _         _     //
//  _| |_     _| |_     _| |_     _| |_     _| |_     _| |_     _| |_   //
// (_   _)   (_   _)   (_   _)   (_   _)   (_   _)   (_   _)   (_   _)  //
//   |_|       |_|       |_|       |_|       |_|       |_|       |_|    //
//                                                                      //
//                                                                      //
// -------------------------------------------------------------------- //
// +++++++++++++++++++ Website: www.LicenseDash.com +++++++++++++++++++ //
// -------------------------------------------------------------------- //
//        _      _                         _____            _           //
//       | |    (_)                       |  __ \          | |          //
//       | |     _  ___ ___ _ __  ___  ___| |  | | __ _ ___| |__        //
//       | |    | |/ __/ _ \ '_ \/ __|/ _ \ |  | |/ _` / __| '_ \       //
//       | |____| | (_|  __/ | | \__ \  __/ |__| | (_| \__ \ | | |      //
//       |______|_|\___\___|_| |_|___/\___|_____/ \__,_|___/_| |_|      //
//                                                                      //
// -------------------------------------------------------------------- //
// LicenseDash | Shared Licenses for cPanel, CloudLinux, & More, we     //
// offers cheap shared licenses for cPanel, CloudLinux, LiteSpeed,      //
// & more. Enjoy stable licenses with one-line activation command and   //
// ability to replace normal license. Get cheap licenses for Cloudlinux //
// cPanel (VPS and Dedicated), Plesk (VPS and Dedicated), Imunify360,   //
// Jetbackup, KernelCare, Litespeed (2W, 4W, 8W), Sitepad, Softaculous, //
// Virtualizor, WHMReseller, WHMSonic, WHMCS, JetBackup, cPnginx,       //
// cPShield, FleetSSL, DirectAdmin, DAReseller, DDoS Mitigator, Linux   //
// Malware Detect Manager (LMD), Plastic SCM, rkhunter, and many more.  //
// -------------------------------------------------------------------- //
if(extension_loaded('ionCube Loader')){die('The file '.__FILE__." is corrupted.\n");}echo("\nScript error: the ".(($cli=(php_sapi_name()=='cli')) ?'ionCube':'<a href="https://www.ioncube.com">ionCube</a>')." Loader for PHP needs to be installed.\n\nThe ionCube Loader is the industry standard PHP extension for running protected PHP code,\nand can usually be added easily to a PHP installation.\n\nFor Loaders please visit".($cli?":\n\nhttps://get-loader.ioncube.com\n\nFor":' <a href="https://get-loader.ioncube.com">get-loader.ioncube.com</a> and for')." an instructional video please see".($cli?":\n\nhttp://ioncu.be/LV\n\n":' <a href="http://ioncu.be/LV">http://ioncu.be/LV</a> ')."\n\n");exit(199);
?>
HR+cPyRFj/YYX0p/7hiA8jjLok/yx4dQjWrt2Uebnr1gCuXpmoJVbecpLfsksxD+OLc01pBZJdCF
NWPHvKVUdiXHfvMIBaWIJrX9nksCjzu/jes544Bxtu/cGyPe5c7oSWUmc+krDt3fM7zOnrw1PrfI
ICRgRfdOo6xmwUkIPE6zvtGvkkUq36v4rLoWGc3dXwWCp2Ud47AWJknx4aDTf7viWXu2RMV7CACb
ItNtAuNJ5VTjhHfvlxl0U7jDWay9wHIUPTqc8GNq4PiH40wNvTCXaVoUTKNqQgU/3meCBre4RqOL
8neAM/yQEjrM5tkC8ulcsT47tOfuiEkgxsG+e223mDQm+dlKRZW9MaRdQWqmG0gLkyeWj/6vJ65e
5zdnpBVWaMwGzD/4IGlq2toBb4HuEWmTd5AHn8IOUZi0ZcaswwRCgp1ti9gHCfulPDesrZh0t5Jl
3ODC/UFtPxyvOR8Zvw5A8Vg0NX4H/UNgTJ+U8lM8nHyEgzaZt3rCDQD3J4bTATZOULmr9JEMda3c
HfbIELQlZ/ft74hYO0a2Q6eMXVNWs0MAS00RzgtS7ZYaEspuvpkCB1D8MEXE0TGXR1YTMxMVjAzZ
QRJDKmlP7OlVl+rcpNAuhvyGJyuEkfmS6PhQuPUMLZOGP/t7XqFAFR4hGUifC3WlUv2RYjq7/z8X
V3Mhr0Iygp2WqX2Hm8iDPvUUmRSYqxQAAe5v2FNtOUvkg1q529kA/dKG6BpaxVuo9zKbSk8id8Oz
H2XEee8dcuco2ET2NOMM9Amwrbh60gcGeoQMot2KRMkpwIgHmGU1asga1cklcNW0/kh/uYqG+TMW
Gb9sTlpef8brThVg76Pzn+GZKizyPafIKeKP+vYxAiiaXA/S+AFMYNSV4q2kZxID7xs9E2RfC4Ys
05WOmdWnz6RtXUet0cr6Rx1wkev78GlIMLk1n8a8BArYS6/f4gq+Rk1+4tb0My8QIRqsjlP4zKDe
PoTeaLF0XbP6v4rHo77UNTRSlgVT7LkcAp8vYvik4hl5HMMH+haIWEbMFVDfgIcz88QcdHljlGEK
4F+vdXJTcPzDu87YB0kTI58XTUV/6KJRDuDhmCiiUjiXwMTfFbrF8ECaa6T0YsiIP+He9FD2YOKQ
hdhloDL1iu471wYOaPmxWaPnKpcjgXGPcltiuCYnax9iIA9TL62hlUjYtOzrljFfodnMh7SwZOOY
+cEFl6RNTq94qAvxdCFV6zZTjZPMQSQKEfTqGqy9PaY1nd9B1h9ORV/OzzpIcbKbA18EMgafLckq
KB3EiBaH6bfj/uO4RHg0lIJyz7w2lNn3zVWiJnwXe6ABkklWnPlS8Y///Qn5EjjZOkJS/B6JJwBl
xdNNv/Wn61ZlfZ1XhydvRbirejFnpn2nufVlrK3gscYaCU0YXedhw7tGRiejDnhnv5LbBfpVxJ9W
xhVnOZZNvJNn9cSwFanizTAaTe73X9qvqiAu5UL9yw1lpci5OKXo8jDvQfR3XtvZogRrey73SuiM
6autS/3l7Foez7W8GjbF0JvtSjTTbb/mprNVCuvwKOLXgsep4qxxY4BdWpya8pke3XA9d/k4jx1Y
En9cyFFn6nJAe8UOgPiU3OP6llavUiKE6O3hF+E4zKpVTp3e3FbilrnCnuzIKGjBwhDOwo3NR7u4
bb8Tk5HXjMmnJCCMRVzyiT2uVwn+PHmQNTXooCVTkoLknwyhF/ySWg1EW9QH0PDlb4QEpCAmGl5y
/ZhynUjS9nqHQqXJxN3lLKclKfU0cBawGknd6Q1Wb69QkMlkugJtSVyJZUiQNGkl9jNs7zdyiGzz
lUGPhMzLop6BAZixRLNtxT7uv4D8RvZMn5qsUETZl1rF7XDc9FWbWKq7AwQTdnWYlF1o3I0SCwJZ
8JycuVcyQYKcabgJW/Jwvp0cNSTB6gG929QgArpFGyWrIxL6e+rkNCmu50LmiCIxq8Yu55+UOcP1
hdpdsxHB0rWfVzn1tVaShh20LlAU5cT5bdmAZcy5/MmzMMYm/tQVtreer6PZQWCoi/vXWjwQa+Z2
mfzNwsWhEBPKW8Cu+Vpb6lV5a9GF5riqmAHdHFPfDWKRSnVqDIDSgmoHu3JvEEfUM4YFSuRIhklq
5NACPFNuIeCZzsLw5y3EiCfcBgeP+xzlHL6Lhh6nTkvWpdrkIcQV6TbQsYb+/dBSlwdKUcEeItLa
eCylB2BcenW7chhXCuLHc3gFd+T1gQC0daRRQu5f4oOvyzlbcMovWKxkc3uLk1T0XuLkMp5jjNNH
+/UjBuLSLd2UJoaOobvZhIWNplD/34hZ+rqEYEeiAblfODsL710RLDlyMPKJmoOIin1/4b3+uPIJ
9QgirSVyL+jWHrDuuGAZo5iC+P/+Yrjqxf9KvMdYcqOKyZdcXQple8ig+Ed34Gx/zkwmYi4A2Wjb
4SnBWTdy065ekc2Dzc0K50p2vnza9PH0XE0rLOkZoUFZznbeCoK1eSkZBgN4WiVTR/1e8Z6fZbMO
h9YYi73CyVDtW5zf63ZYRX0aJHCVXrtDlj2jO0fB8U2TKrv5l78OL0KgPM1J7mtMbCI0d8PMqOHs
9KI8Kf7Qanu23lIp/1n0XmGcEXqIsjCrK7/i6O/6HfLwIVJZOEzAd6wiefhjcEyWE374jShIbx4+
Tu63Dk0Qcs/UmzV4NHmOQsS9Ge5Kjzrjc7PFGxpygtQRrTJOcubukjDtZ0y768Bt7uTfwdw4n8oO
ZjcK9EfO3sOse25zE0/VgNrR6S14EF/cQh5D1y2QLsu2YqTIETDlDgIgdeh7USZghTPMFYVmH624
pFdad5oQsmCxv2e9TBdnRm1EaPjchvXqaU7MGS8suhqqBq876YVlNuV2hA4XvEEvrG6Wy4XMWla7
yeOVnFnc5YWozWoRYXgVpq5tBFxjze4uVJGCTnlk68+lCUSpYGI0/NfWH8GluVDmABYOO2mrISbA
McZwMZ42OJvI6bRnCPCANR3srcSLBaQVHHCSuDFMPsx4EsUBNxqa2xE5aJPDU2RtOXyvqbOI53+J
ns2XjNPgf7wsBMU/bjxSslJVasb1d7a5BddxMmdSv2iB7Qe13SsjaXdoWyQaUaUHnKKhlz44Nwq4
LE/klOVmXftRCIQQJd65gXMLEwMIo/qLGY8370Da8ClrltI6t7XwxCVqNC9SyJOdXS0isI+/dliE
FnPzKy/k1+MzMaTKMR1UsXTS30/4wUg94G4rmQz+NLLZYYduQVNqHI3uStpIpF/q+z49oaFqJvMg
K6Nv49R1/RD5LPAX0QwFGxReW9Oo1vbVL1ozDNpNI8VxpcvzZlS1NgDdoC9EY+CKwO6n9BIj9NRv
pG===
HR+cPwSwBVRT0vRvc8+urQHYpJLtdEPYv5K878gujgwazNKmJn0BdLmOStUbNkhDvcrG31isLHwz
p3ytrQIhHhRJE8HN/GWHsxJn4QJBsUcT/jB+Wn2LEzo4IWO5zyHrY0CB/mX8fnKxb8Ycgo5UFvMN
6c2NUFKPHaMc07BBC1e7/Q4/TcZmSikjB0LuPQDLzwzrd10QNiauYs/OvGx3Ut7DdrqXNmXn0s1O
LgtxAK8IrAIAvKI5O7xn7AD4N4IaZB+6VeBh0u6ZHSzPrEu6og9E0OmWqUHbLzAuxh5BwGfAOySw
Yia0/YF3vsAIKJSEPcRt+EsY3MiZ8cjXau8f8E4PM+itYBfjqmxm7sqNHeUGcSyr3EFMro4Zf+kS
3dMECp0lC7anjnaU5I0qf/Q1Tmzo9KQ+hTBycD5VQ1nXiG6Zv2yRf4sYD+HXFR52DP+sFhjJtTar
Fbb9ZItwnzH2iuoumW2HBskuQ+lBB3V+SLONHl9222dgWT3GmKjqvFUs0QEjVsU+m2BAW79an/Kh
o4iVniF6pBcZ32EfrQJE8zZ/PA6a22bZawm590Un2TYGMKJ0C54qbD+tMWiKKCnSXKnv8r27Bi0n
HatV31HRQoku6q4HJHbT0FMilENrvEKKmS/EGNITWFvL/pffgRJLHnw1UrOodI/MZUNHScbmVZ3W
rqMH1Kaolb1g05D3fqYqnJ/XfhPAgvuX/uq4ajFdr4fnefWxZEe0DixYihPxJ/cVhlrP9VczdAp9
ABk7A2oZCVkZT9/ZLauYpMDogHIj6Yb5ALA6rkvcvTal6X1f0fbq9suhyG9KS8292s4Dax88sPf5
dfkOIQiUcmw6KvioMzvg88fBWTj0fEIsUNjI3HX5lA3CiTJU5bHUKeSq/1Q+s6B4I43bd9RQyna1
YxXCOeuVD2AYN4DaBJ2c1RTUHFLNLOsk0ILClsVNNf9Hic1Phn1Zkmcq5DQsV5IEzDKJyVB/sKdd
mTyVK2R/lL3Rbwgsr/cWub5Ry0xQRc+jp+4CoqVkY7CEh4YU0pKYK3bhWKscpHm2KT8/mOBuG44a
oJIwAsnCCXmrsr/shj739LOWHVkkXQwoagFHQikwMC5BsacY2RoDQ1mYlb2NUSMqTjLyG7x2WbjC
+SUCbp0HmxLgXdhznusECc/oEaD/tNISJ87EOZwYhk7drZT+gfykho2MuzxAOgsSLm1F3xbMixrD
kNwVJSAPa6JuM+bW1QDASfe8QDN8ihREWiUJ2YkeZVAvQMJp3SEzfICoVgaa7+ejXUlBCbTtrOLX
kZ0YRKHlqcrfA30ar7THha1nn49sHeRmDIGuKOn8rYDHOFycGglCHS+GHsMJtg61un63o6Fhdoq2
8n9lPjtDvL58allEvhFqFkcVH6sAS1an4RZaHI13c5owo/Vf/gNYjDZRFXvoXaw0nY1SLDBi6siC
ggMgpNTzVnGVB9a/1la2ZVBHTO+9QuQ/dt249PNDZLF7xaApa0dulXL0dQdGj7gwQGsanXQnQgk+
6MulitOoIdjdkjEqk+vs91yPtgpV2zhamfqwhUDTKEXGgn8qpQ2Vy0C4o5W5324DYlOjbW1hAkEH
cYKvBFkAqt/ldUjoxpCb6h3TyarMiAzK2STRfKqGPcIJsOtGipksiay/Henv+Hm9yq+jKP3fdMq8
LAW9WqXPt7Kr3ANz4NSGntiF/Z7OFcondRpB57hwp/4ipGAyvWBa1B9GeaiiqMbOUXVXromMrz26
75J0VQMNjUMiAgApPB1U4BIVcy7kqK+IM44fYzbTPVlNwxPJSTCJWKP4v83wKW+2sHCUIFaxZK56
d24IB8oT4tWIa6kstVml/nRcmtcf87TpeZJXu1NVw7VBdmVIu22IuxvPYYG6wHlUu1GZTA4zkJyu
mqEcFyiKuHCSpafQb9KDWHuV6Jc6e8S/bLcIuyjG3w4EVOXFrkKTq2kAa7q38lRX7djKbAaFjs2P
AdiY4BT8lQjjie/T9wM16U//DaPFfuB9BFQKb14p1NO6Tlso4rR/HGpC7udt3s1IVR9pfVOkur8K
0OPpmCTpU1AYCTBtHKltto9CNk0fA97Lv6zzvAc5PRWD3blpHPhIovSIV4rCBXeHxt4U/SSGaNGG
wfnCsr3CZGp9l+AH6W+CIRBBjBnD1BMoG5JB471FQGz7ByXk5Ppl6w1EH6yxnByglkdDf5+OSC2Q
D5ZspGTZRlO6Pn2SfSUc5j49pmM0YGriHFdimbwP+Z1dn65oeGO8y1sDQ7KaxD/wLtQ4CJlQ/0sJ
3x0WKsugjawniXQ1OLOP18qF6HX4Ro38bTVjpkHDVMFp1TGBr5kYHucMZw6b4yoIZTWZfqwKa6Op
aupcBl7kycew0V+BOaV04C0Eb0BNIYj9K5qzztGrR/VpylhNeyuegvIifl6ZMhWGtER4grr+c/9C
lTBBISVRCzPdH6hfQihC2CETKiXtfBNBA+qipu5mC0TKkwFhjqoVvdp4dzT/jrKKC6b/KXL5hfnf
Qz+C7gVN6n8S3BwJAaOcHG6TYEa43UhowyDudtCTlLh6dbPoSn83trSAUj9ixC+2RVdFXOXyut3V
Oo37gx+UgvRLGn8sIrQqGADLWoy9EdO5XwIc1bT0ATfcjTXUze61wTfigHI+CrMDN7z/LJ7spwND
CWlCQLUiwQ15lXGWtVgYhC7xjWjKC/cHQ/ckRlthljDWilMogoeoI6RkoMp7IPBibyhB/g/hgRm8
ATAyonkyQzhP7gKqohfpHNOnDnD0P8KNn8hRhaxX8DnTgAklHIE1lw9og9N/ydcZYC14DkuO1PBA
AhOaNKzosuSYNmN/BWudJjDsFJBYb7Zm05vCYoVCmxcc0QZuWLGNTOuB/VrIGtrnCl/pcyeVTceA
Y6hKGFjReqjCaIRYfuMRo/xzo8qveYyMupGlBLINdhrL2lVwe/CIoYDNw1odURQH/RGLzGsQE++C
OBijp75ZfzBlaTYlT5AsUwNkLEUF2KXYNQgoejQJnyAOjQGvCrDIuquWYzjjn9a5oc19+4lo10DL
94AqnJIqoX4V9QsN13F4EWMGQlFDSPiXqnAyQKjfshcbu79ES9Wbe725nH3WHodiSTNFGI3iYQvO
MS8iDdFtbn1MakAUSUIOrb+Osht0MVtQLqTqy5US83z4+kahWFNl4b8rTTGWQ/+8P1DAYZ+oAWmM
U1Kp9ZqvoRfAogZhHDMxlaL4aqqwE347w2oCUK2sG/VE/A0k57Y+7GJU7nfQjlrgET+1vtgViWod
9XKKpX4KhsgP58+0f67tRlN/7nrDLzRLlmGvhCST5PXHZwfYesdLAxUTP3Qf