[phases.setup]
nixPkgs = [
  "php81",
  "php81Extensions.pdo",
  "php81Extensions.pdo_mysql",
  "php81Extensions.gd",
  "php81Extensions.openssl",
  "php81Extensions.mbstring",
  "php81Extensions.iconv",
  "php81Extensions.xml",
  "php81Extensions.xmlwriter",
  "php81Extensions.xmlreader",
  "php81Extensions.ctype",
  "php81Extensions.curl",
  "php81Extensions.zip",
  "wget",
  "curl"
]

[phases.install]
cmds = [
  "chmod +x install-ioncube.sh || true",
  "./install-ioncube.sh || true"
]

[start]
cmd = "php -S 0.0.0.0:$PORT router.php"

