<form name="login" method="post" <?php if ($form_action) echo "action='$form_action'"; ?> class="frm-single"
      data-options="<?php p(json_encode([
          'show_recaptcha' => (bool)$showRecaptcha,
          'recaptcha_key' => $di->recaptcha->getPublicKey(''),
          'recaptcha_theme' => $di->config->get('recaptcha-theme', 'light'),
          'recaptcha_size' => $di->config->get('recaptcha-size', 'normal'),
          'recaptcha_hl' => $di->locale->getId(),
      ])) ?>">
<div class="inside">
    <div class="title"><strong>Toolssandesh</strong></div>
    <div class="frm-title">Login</div>
    <?php if (empty($_GET)) include $this->_script('_error.phtml'); ?>
    <div class="frm-input">
        <input type="text" id="amember-login" name="<?php p($loginFieldName) ?>" class="frm-inp" size="15" value="<?php p($loginFieldValue) ?>" autofocus="autofocus"  placeholder="<?php __e('Username/Email') ?>" autocomplete="username" /><i class="fa fa-user frm-ico"></i>
    </div>
    <div class="frm-input">
        <input type="password" id="amember-pass" name="<?php p($passFieldName) ?>" class="frm-inp" size="15" placeholder="<?php __e('Password') ?>" autocomplete="current-password" /><i class="fa fa-lock frm-ico"></i>
    </div>
    <div class="clearfix margin-bottom-20">
        <div class="pull-left">
        </div>
        <div class="pull-right"><a href="login?sendpass" class="a-link"><i class="fa fa-unlock-alt"></i>Forgot password?</a></div>
    </div>
    <input type="submit" class="frm-submit" value="Login">
    <a href="signup" class="a-link"><i class="fa fa-key"></i>New User? Register.</a>
    <div class="frm-footer">© Toolssandesh - 2025</div>
</div>
</form>