<!DOCTYPE html>
<html class=" "><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php p(isset($meta_title) ? $meta_title : $title) ?></title>
    <?php $this->printLayoutHead(); ?>

    <link rel="stylesheet" href="<?php p($this->_scriptCss("style.min.css")); ?>?v=1">
    <link rel="stylesheet" href="<?php p($this->_scriptCss("jquery.mCustomScrollbar.min.css")); ?>">
    <link rel="stylesheet" href="<?php p($this->_scriptCss("waves.min.css")); ?>">
    <link rel="stylesheet" href="<?php p($this->_scriptCss("sweetalert.css")); ?>">
    
    <style>
        .radio.am-el-checked {
          border: 2px solid #ff7052;
       }
    </style>
</head>
<body class="am-page-signup am-page-signup-default">
<div class="row small-spacing">
    <div class="col-12">
        <div class="invoice-box">
            <div class="inside">
                <div class="title" style="text-align: center;font-size: 30px;"><strong>Toolssandesh.com</strong></div>
                <div class="frm-title" style="text-align: center;padding: 15px 0px 40px 0px;">Register</div>

    <?php echo $content ?>
</div>
<script type="text/am-vars">{"script-replaced-_login":"1","showRecaptcha":false,"recaptchaPublicKey":null}</script>
<div id="am-flash" class="am-flash">
    <div class="am-flash-mask"></div>
    <div class="am-flash-content"></div>
</div>
<script src="<?php p($this->_scriptJs("bootstrap.min.js")); ?>" type="text/javascript"></script>
<script src="<?php p($this->_scriptJs("jquery.mCustomScrollbar.concat.min.js")); ?>" type="text/javascript"></script>
<script src="<?php p($this->_scriptJs("nprogress.js")); ?>" type="text/javascript"></script>
<script src="<?php p($this->_scriptJs("sweetalert.min.js")); ?>" type="text/javascript"></script>
<script src="<?php p($this->_scriptJs("waves.min.js")); ?>" type="text/javascript"></script>
<script src="<?php p($this->_scriptJs("main.min.js")); ?>" type="text/javascript"></script>
</body></html>
