<!DOCTYPE html>
<html class=" "><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php p(isset($meta_title) ? $meta_title : $title) ?></title>
    <?php $this->printLayoutHead(); ?>

    <link rel="stylesheet" href="<?php p($this->_scriptCss("style.min.css")); ?>?v=1">
    <link rel="stylesheet" href="<?php p($this->_scriptCss("jquery.mCustomScrollbar.min.css")); ?>">
    <link rel="stylesheet" href="<?php p($this->_scriptCss("waves.min.css")); ?>">
    <link rel="stylesheet" href="<?php p($this->_scriptCss("sweetalert.css")); ?>">
    
    
</head>
<body>
<div id="single-wrapper">
    <?php echo $content ?>
</div>
<script type="text/am-vars">{"script-replaced-_login":"1","showRecaptcha":false,"recaptchaPublicKey":null}</script>
<div id="am-flash" class="am-flash">
    <div class="am-flash-mask"></div>
    <div class="am-flash-content"></div>
</div>
<script src="<?php p($this->_scriptJs("bootstrap.min.js")); ?>" type="text/javascript"></script>
<script src="<?php p($this->_scriptJs("jquery.mCustomScrollbar.concat.min.js")); ?>" type="text/javascript"></script>
<script src="<?php p($this->_scriptJs("nprogress.js")); ?>" type="text/javascript"></script>
<script src="<?php p($this->_scriptJs("sweetalert.min.js")); ?>" type="text/javascript"></script>
<script src="<?php p($this->_scriptJs("waves.min.js")); ?>" type="text/javascript"></script>
<script src="<?php p($this->_scriptJs("main.min.js")); ?>" type="text/javascript"></script>
</body></html>
